replicaCount: 2

image:
  repository: myregistry/ev-management
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
  hosts:
    - host: ev-management.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

config:
  ENVIRONMENT: "dev"

secrets:
  DATABASE_PASSWORD: "changeme"
