services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  postgres:
    image: postgis/postgis:17-3.4
    #    image: postgres:17
    environment:
      POSTGRES_USER: ev_management_user
      POSTGRES_PASSWORD: A35Hj5e%^Z
      POSTGRES_DB: ev_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ~/Downloads/Electric_Vehicle_Population_Data.csv:/tmp/Electric_Vehicle_Population_Data.csv
  #      - schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
    driver: local
