networks:
  ev_management_network:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ev_management_network

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - ev_management_network
  postgres:
    image: postgis/postgis:17-3.4
    container_name: postgresql
    environment:
      POSTGRES_USER: ev_management_user
      POSTGRES_PASSWORD: A35Hj5e%^Z
      POSTGRES_DB: ev_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
    networks:
      - ev_management_network

volumes:
  postgres_data:
    driver: local