apiVersion: v1
kind: Service
metadata:
  name: {{ include "ev-management.fullname" . }}
  labels:
    name: {{ include "ev-management.name" . }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "ev-management.name" . }}
